import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SessionProvider from '@/app/components/SessionProvider';
import Header from '@/app/components/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className='flex min-h-full flex-col'>
        <SessionProvider>
          <Header />
          <main className='grow'>
          {children}
          </main>
        </SessionProvider>
        </body>
    </html>
  )
}
